gitlab:
  #image: gitlab/gitlab-ce
  image: 'twang2218/gitlab-ce-zh:11.1.4'
  hostname: git.example.com
  environment:
    TZ: 'Asia/Shanghai'
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://git.example.com'
      gitlab_rails['gitlab_shell_ssh_port'] = 2222
      unicorn['port'] = 8888
      nginx['listen_port'] = 80
  ports:
    - "80:80"
    - "443:443"
    - "2222:22"
  volumes:
    - ./config:/etc/gitlab
    - ./logs:/var/log/gitlab
    - ./data:/var/opt/gitlab
  restart: always
